### ISSUE TITLE
Squashing "INFO: uncertainty should have attribute uncertainty_type." messages

### ISSUE THREAD

**Issue by byrdie** [sunpy/irispy#105]
Using `read_iris_spectrograph_level2_fits()` throws many
```
INFO: uncertainty should have attribute uncertainty_type. [astropy.nddata.nddata]
``` 
messages. This makes it inconvenient to see other outputs of my program. Is there an efficient way to squash this message or fix the uncertainty parameter so `astropy` doesn't complain?

**Comment by DanRyanIrish** [comment]
This may help you to suppress the warnings so they are not printed to your screen: https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings
