### ISSUE TITLE
Creation of an IRISSpectrogramSequence to Include Calibration and Unit Conversion Functionality

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/irispy#25]
A new ```IRISSpectrogramSequence``` should be written to replace the use of ```SpectrogramSequence``` in ```IRISSpectrograph```.  ```IRISSpectrogramSequence``` should be subclassed from ```SpectrogramSequence``` and provide the following additional functionalities:
* radiometric calibration
* residual wavelength calibration
* intensity fractional uncertainty
* conversion between DN and photons
* exposure time correction

Functions for many of these already exist in iris_tools.py.  ```IRISSpectrogramSequence``` should include wrappers around these that also perform required housekeeping, e.g. keep track of units.

For more detail on methodologies, see  http://iris.lmsal.com/itn26/calibration.html

**Comment by ehsteve** [comment]
See http://iris.lmsal.com/itn26/calibration.html
