### ISSUE TITLE
SJICube.plot() Not Returning an Animation

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/irispy#31]
I tried running ```SJICube.plot()``` to get an animation.  It says it returns a FuncAnimation but is only showing one image and has no sliders.  I'm running it in a jupyter notebook.  I also tried animating it manually using ```sunpy.visualization.imageanimator.Imageanimator``` and it worked fine.  So it's not a jupyter notebook issue.

**Comment by sjtimothy** [comment]
I keep getting this error. It seems updatefig is having trouble updating the axes...

~/Developer/sunpy_dev/sunpy/map/mapcube.py in updatefig(i, im, annotate, ani_data, removes)
    219             if wcsaxes_compat.is_wcsaxes(axes):
    220                 im.axes.reset_wcs(ani_data[i].wcs)
--> 221                 wcsaxes_compat.default_wcs_grid(axes)
    222             else:
    223                 im.set_extent(np.concatenate((ani_data[i].xrange.value,
TypeError: default_wcs_grid() missing 2 required positional arguments: 'units' and 'ctypes'

**Comment by DanRyanIrish** [comment]
@sjtimothy Can you supply the code you ran to get this error?  I didn't get this error, but there definitely seems to be something up with this function.  Perhaps @ehsteve can take a look when he's back from his travels.

**Comment by sjtimothy** [comment]
Sure, this was using a locally saved fits file, not the sample data

from irispy.sji import SJICube, SJIMap
import matplotlib.pyplot as plt
import matplotlib.animation as animation

local='/Users/shelbe/Documents/IRIS/data/AR12661/'
import os
sji_flist=[]
for file in os.listdir(local):
    if file.endswith(".fits"):
        sji_flist.append(os.path.join(local, file))

mc=SJICube(sji_flist[0])
mc.plot()

**Comment by sjtimothy** [comment]
I also tried plotting a slice of the map cube and got a different error:

mc[0:10].plot()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-125-520746cb0c4c> in <module>()
----> 1 mc[0:10].plot()

~/Developer/irispy/irispy/sji.py in __getitem__(self, key)
    210             return self._get_map(key)
    211         elif isinstance(key, slice):
--> 212             return SJICube((self.data[key, :, :], self._meta[key]))
    213 
    214     def __len__(self):

~/Developer/irispy/irispy/sji.py in __init__(self, input)
    194         cmap = []
    195         for i in range(number_of_images):
--> 196             norm.append(deepcopy(self[i].plot_settings['norm']))
    197             cmap.append(deepcopy(self[i].plot_settings['cmap']))
    198 

~/Developer/irispy/irispy/sji.py in __getitem__(self, key)
    208         work.  Otherwise, a mapcube is returned."""
    209         if isinstance(key, int):
--> 210             return self._get_map(key)
    211         elif isinstance(key, slice):
    212             return SJICube((self.data[key, :, :], self._meta[key]))

~/Developer/irispy/irispy/sji.py in _get_map(self, index)
    201 
    202     def _get_map(self, index):
--> 203         return SJIMap(self.data[index, :, :], self._meta[index], mask=self.mask[index, :, :])
    204 
    205     def __getitem__(self, key):

AttributeError: 'SJICube' object has no attribute 'mask'

**Comment by DanRyanIrish** [comment]
FYI: When typing out code in GitHub Issues, PRs, etc., you can bookend the code snippet with three tickmarks, `, (N.B. not quotation marks) to make it cleat that it's code.  For example
```mc[0:10].plot()```

Regarding the above plot error, I think you have to create a submap of the region you are interested in and then try plotting the submap.  Perhaps @ehsteve can give more advice on the next call.

**Comment by shelbej** [comment]
When trying to run image coalignment on the map cube, I get this error:
'''AttributeError: 'SJICube' object has no attribute 'maps''''

Could this be related to the plotting errors? Should we add a maps attribute?

**Comment by shelbej** [comment]
animation bug fix #62
