### ISSUE TITLE
Better reprs

### ISSUE THREAD

**Issue by Cadair** [sunpy/irispy#35]
Objects should `__repr__` well, this means calling `super()__repr__()` as the first line of a `__repr__` method, and also defining `_repr_html_` where appropriate to make pretty output for the notebook.

@abit2

**Comment by Cadair** [comment]
same applies to cube.

**Comment by DanRyanIrish** [comment]
Hi @Cadair.  Just looking over some old issues.  I haven't used __repr_hmtl__ before.  When would you say it is appropriate to make these?

**Comment by Cadair** [comment]
Anything where having more than plain text would be good. So tables or maths etc.
